## NUMPY ARRAYS

In [3]:
import numpy as np

In [4]:
list=[1,2,3,4,5,6,7,8,9]
list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
np.array(list)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
nested_list=[[1,2],[5,8],[5,12]]
nested_list

[[1, 2], [5, 8], [5, 12]]

In [7]:
np.array(nested_list)

array([[ 1,  2],
       [ 5,  8],
       [ 5, 12]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((4,1))

array([[1.],
       [1.],
       [1.],
       [1.]])

In [13]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(3)

array([0.33269395, 0.77435668, 0.19180322])

In [16]:
np.random.rand(3,4)

array([[0.86192762, 0.41372008, 0.75062307, 0.90669672],
       [0.79437564, 0.84384507, 0.08570675, 0.01020334],
       [0.23108537, 0.43119488, 0.01851486, 0.53226225]])

In [17]:
np.random.randn(5,3)

array([[ 0.21274611,  0.79118718,  0.3332775 ],
       [-0.96983092,  1.05971793,  1.07383409],
       [-1.07038858,  2.02705597,  1.48962924],
       [ 1.39535978, -0.36038821,  0.35806707],
       [-0.88292028, -1.35834377,  0.67828122]])

In [18]:
np.random.randint(1,80,5)

array([69, 47,  5, 59, 63])

In [19]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [20]:
arr=np.random.rand(4)
arr

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [21]:
arr.reshape(2,2)

array([[0.15601864, 0.15599452],
       [0.05808361, 0.86617615]])

In [22]:
arr.max()

0.8661761457749352

In [23]:
arr.argmax() #indexmax

3

In [24]:
arr.min()

0.05808361216819946

In [25]:
arr.argmin() #indexmin

2

In [26]:
arr.dtype

dtype('float64')

## NUMPY INDEX SELECTION

In [27]:
arr=np.random.rand(11)
arr

array([0.60111501, 0.70807258, 0.02058449, 0.96990985, 0.83244264,
       0.21233911, 0.18182497, 0.18340451, 0.30424224, 0.52475643,
       0.43194502])

In [28]:
arr[8]

0.3042422429595377

In [29]:
arr[2]

0.020584494295802447

In [30]:
arr[0:3]=5
arr

array([5.        , 5.        , 5.        , 0.96990985, 0.83244264,
       0.21233911, 0.18182497, 0.18340451, 0.30424224, 0.52475643,
       0.43194502])

In [31]:
arr>1

array([ True,  True,  True, False, False, False, False, False, False,
       False, False])

In [32]:
arr<5

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True])

## NUMPY OPERATIONS

In [33]:
arr=np.random.rand(10)
arr

array([0.29122914, 0.61185289, 0.13949386, 0.29214465, 0.36636184,
       0.45606998, 0.78517596, 0.19967378, 0.51423444, 0.59241457])

In [34]:
arr+3

array([3.29122914, 3.61185289, 3.13949386, 3.29214465, 3.36636184,
       3.45606998, 3.78517596, 3.19967378, 3.51423444, 3.59241457])

In [35]:
arr-5

array([-4.70877086, -4.38814711, -4.86050614, -4.70785535, -4.63363816,
       -4.54393002, -4.21482404, -4.80032622, -4.48576556, -4.40758543])

In [36]:
arr/4

array([0.07280729, 0.15296322, 0.03487347, 0.07303616, 0.09159046,
       0.1140175 , 0.19629399, 0.04991845, 0.12855861, 0.14810364])

In [37]:
np.sin(arr)

array([0.28712982, 0.5743852 , 0.13904191, 0.28800666, 0.35822109,
       0.44042319, 0.70694964, 0.19834961, 0.49186844, 0.55836576])

In [38]:
np.log(arr)

array([-1.2336449 , -0.49126339, -1.96973469, -1.23050623, -1.00413379,
       -0.78510901, -0.24184743, -1.61107033, -0.66507601, -0.5235486 ])

In [39]:
arr.sum()

4.248651122445437

In [40]:
arr.var()

0.037286559308904496

In [41]:
arr.std()

0.19309727939280888

In [42]:
arr_2d=arr.reshape(2,5)

In [43]:
arr_2d.sum(axis=0)

array([0.74729912, 1.39702886, 0.33916764, 0.80637909, 0.95877641])

In [44]:
arr_2d.sum(axis=1)

array([1.70108239, 2.54756874])